# snapcraft.yaml - builds a Snap package of the JavaFX application
# Copyright (C) 2020-2021 John Neffenger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: hello-javafx
title: Hello JavaFX!
summary: Sample JavaFX application
description: |
  This project is my template for building and packaging JavaFX
  applications. It follows the conventions of Apache Maven for its
  directory structure and includes a sample application that prints
  "Hello World!" to standard output when its button is pressed.

  For more information, including the source code and build files,
  see the README file for this project on GitHub:

  https://github.com/jgneff/hello-javafx

  Java and OpenJDK are trademarks or registered trademarks of Oracle
  and/or its affiliates.
version: '1.0.0'
license: GPL-3.0+

base: core20
grade: stable
confinement: strict

architectures:
- build-on: amd64

apps:
  hello-javafx:
    command: bin/HelloJavaFX
    environment:
      LC_ALL: C.UTF-8
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - x11
    - opengl
  java:
    command: bin/java
    environment:
      LC_ALL: C.UTF-8

parts:
  lib:
    plugin: nil
    # Adds Snapcraft list of missing libraries plus
    # libcanberra-gtk-module and libcanberra-gtk3-module
    stage-packages:
    - libasound2
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libcairo-gobject2
    - libcairo2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libfribidi0
    - libgdk-pixbuf2.0-0
    - libgl1
    - libglvnd0
    - libglx0
    - libgraphite2-3
    - libgtk-3-0
    - libgtk2.0-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libx11-6
    - libxau6
    - libxcb-render0
    - libxcb-shm0
    - libxcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    - libxtst6
    - libcanberra-gtk-module
    - libcanberra-gtk3-module

  app:
    after: [lib]
    plugin: make
    source: .
    source-type: local
    build-environment:
    - JAVA_HOME: /snap/openjdk/current/jdk
    build-snaps: [openjdk/latest/candidate, openjfx/latest/candidate]

  del:
    after: [app]
    plugin: nil
    # Deletes files and links already available in the base snap
    override-prime: |
      set -o xtrace
      cd $SNAPCRAFT_PRIME
      base=/snap/core20/current
      find * -type f -exec test -f "$base/{}" \; -delete
      find * -type l -exec test -L "$base/{}" \; -delete
      find * -type d -empty -exec test -d "$base/{}" \; -delete

layout:
  # libGL error: MESA-LOADER: failed to open iris, swrast
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  # Gtk-Message: Failed to load module "canberra-gtk-module"
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0/modules:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0/modules
